// ═══════════════════════════════════════════════════════════
// ══  BAKER DAILY — Living Daily Note  ══════════════════════
// ═══════════════════════════════════════════════════════════
// Creates and maintains a daily note in 00-Capture/YYYY-MM-DD.md
// Pre-populated from: split, tasks, weather, academic, biometrics
// Updated live as the day progresses
// Morning briefing generated by Claude on first open
// ═══════════════════════════════════════════════════════════
var DAILY=(function(){

  var _today=null;
  var _briefCache=null;
  var _writtenToday=false;
  var _lastUpdate=0;

  function _dateStr(){return new Date().toISOString().slice(0,10);}
  function _timeStr(){var d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
  function _dayName(){return['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][new Date().getDay()];}

  // ── Build the daily note markdown ─────────────────────────
  async function _buildNote(briefing){
    var date=_dateStr();
    var day=_dayName();
    var time=_timeStr();

    // ── Frontmatter ───────────────────────────────────────
    var md='---\n';
    md+='type: daily\n';
    md+='date: '+date+'\n';
    md+='day: '+day+'\n';
    md+='created: '+time+'\n';
    md+='---\n\n';

    // ── Title ─────────────────────────────────────────────
    md+='# '+day+', '+date+'\n\n';

    // ── Morning Briefing ──────────────────────────────────
    md+='## Morning Briefing\n\n';
    if(briefing){
      md+='>'+briefing.split('\n').join('\n>')+'\n\n';
    }else{
      md+='> BAKER briefing pending...\n\n';
    }

    // ── Weather ───────────────────────────────────────────
    try{
      var wx=localStorage.getItem('baker_weather_cache');
      if(wx){
        var wxd=JSON.parse(wx);
        md+='## Weather — Oscoda, MI\n\n';
        md+='**'+Math.round(wxd.temp||0)+'°F** — '+(wxd.desc||'')+'  \n';
        md+='High '+Math.round(wxd.high||0)+'°F / Low '+Math.round(wxd.low||0)+'°F  \n';
        if(wxd.precip)md+='Precip: '+wxd.precip+'%\n';
        md+='\n';
      }
    }catch(e){}

    // ── Today's Workout ───────────────────────────────────
    try{
      var stData=JSON.parse(localStorage.getItem('baker_strength_v1')||'{}');
      var todayDayIdx=new Date().getDay();
      var splitDay=(stData.split||[]).find(function(s){return s.day===todayDayIdx;});
      md+='## Workout — '+(splitDay?splitDay.name:'Rest Day')+'\n\n';
      if(splitDay&&splitDay.exercises&&splitDay.exercises.length){
        splitDay.exercises.forEach(function(ex){
          // Check if already logged
          var log=(stData.logs||[]).find(function(l){return l.date===date;});
          var entry=log&&log.entries.find(function(e){return e.exercise===ex.name;});
          var doneSets=entry?entry.sets.filter(function(s){return s.done;}).length:0;
          var total=entry?entry.sets.length:ex.sets;
          var check=doneSets>=total?'[x]':'[ ]';
          md+='- '+check+' **'+ex.name+'** '+ex.sets+'×'+ex.reps;
          if(ex.weight)md+=' @ '+ex.weight+'lbs';
          if(doneSets>0&&doneSets<total)md+=' _('+doneSets+'/'+total+' sets)_';
          md+='\n';
        });
      }else{
        md+='_Rest day — recovery, mobility, hydration._\n';
      }
      md+='\n';
    }catch(e){md+='## Workout\n\n_Data unavailable_\n\n';}

    // ── Tasks Due Today ────────────────────────────────────
    try{
      var calData=JSON.parse(localStorage.getItem('baker_cal_v1')||'[]');
      var dueToday=calData.filter(function(t){return!t.done&&t.due&&t.due===date;});
      var overdue=calData.filter(function(t){return!t.done&&t.due&&t.due<date;});
      var pending=calData.filter(function(t){return!t.done&&!t.due;});

      md+='## Tasks\n\n';
      if(overdue.length){
        md+='### ⚠ Overdue\n\n';
        overdue.slice(0,5).forEach(function(t){md+='- [ ] '+t.text+' _(was '+t.due+')_\n';});
        md+='\n';
      }
      if(dueToday.length){
        md+='### Due Today\n\n';
        dueToday.forEach(function(t){md+='- [ ] '+t.text+'\n';});
        md+='\n';
      }
      if(pending.length){
        md+='### Backlog\n\n';
        pending.slice(0,8).forEach(function(t){md+='- [ ] '+t.text+'\n';});
        md+='\n';
      }
      if(!dueToday.length&&!overdue.length&&!pending.length){
        md+='_No pending tasks. Inbox zero._\n\n';
      }
    }catch(e){md+='## Tasks\n\n_Data unavailable_\n\n';}

    // ── Academic ──────────────────────────────────────────
    try{
      var acData=JSON.parse(localStorage.getItem('baker_academic_v1')||'{}');
      var upcoming=[];
      var soon=new Date();soon.setDate(soon.getDate()+7);
      var soonStr=soon.toISOString().slice(0,10);
      (acData.classes||[]).forEach(function(cls){
        (cls.assignments||[]).filter(function(a){
          return !a.done&&a.due&&a.due>=date&&a.due<=soonStr;
        }).forEach(function(a){
          upcoming.push({class:cls.name,name:a.name,due:a.due});
        });
      });
      if(upcoming.length){
        upcoming.sort(function(a,b){return a.due<b.due?-1:1;});
        md+='## Academic — Upcoming (7 days)\n\n';
        upcoming.forEach(function(a){
          var daysLeft=Math.ceil((new Date(a.due)-new Date(date))/(1000*86400));
          var urgency=daysLeft<=1?'🔴':daysLeft<=3?'🟡':'🟢';
          md+='- '+urgency+' **['+a.class+']** '+a.name+' — due '+a.due+(daysLeft===0?' _(today)_':daysLeft===1?' _(tomorrow)_':' _('+daysLeft+'d)_')+'\n';
        });
        md+='\n';
      }
    }catch(e){}

    // ── Habits ────────────────────────────────────────────
    try{
      var habData=JSON.parse(localStorage.getItem('baker_habits_v1')||'{}');
      if(habData.habits&&habData.habits.length){
        md+='## Habits\n\n';
        var todayLog=(habData.log||{})[date]||{};
        habData.habits.forEach(function(h){
          var done=!!todayLog[h.id];
          md+='- ['+(done?'x':' ')+'] '+(h.emoji?h.emoji+' ':'')+h.name+'\n';
        });
        md+='\n';
      }
    }catch(e){}

    // ── Biometrics (filled in as day goes on) ─────────────
    try{
      var bioData=JSON.parse(localStorage.getItem('baker_biometrics_v1')||'[]');
      var todayBio=bioData.find(function(e){return e.date===date;});
      md+='## Daily Log\n\n';
      md+='| Metric | Value |\n|---|---|\n';
      md+='| Mood | '+(todayBio&&todayBio.mood!=null?todayBio.mood+'/10':'—')+' |\n';
      md+='| Sleep | '+(todayBio&&todayBio.sleep!=null?todayBio.sleep+'h':'—')+' |\n';
      md+='| Energy | '+(todayBio&&todayBio.energy!=null?todayBio.energy+'/10':'—')+' |\n';
      md+='\n';
    }catch(e){}

    // ── Inbox captures today ──────────────────────────────
    try{
      var inboxData=JSON.parse(localStorage.getItem('baker_inbox_v1')||'[]');
      var todayInbox=inboxData.filter(function(i){return i.date===date&&!i.processed;});
      if(todayInbox.length){
        md+='## Captures\n\n';
        todayInbox.forEach(function(i){md+='- [ ] '+i.text+' _('+i.ts+')_\n';});
        md+='\n';
      }
    }catch(e){}

    // ── Notes section (blank for manual notes) ────────────
    md+='## Notes\n\n\n\n';
    md+='---\n*Generated by BAKER · '+date+' '+time+'*\n';

    return md;
  }

  // ── Write to vault ────────────────────────────────────────
  async function _writeToVault(content){
    if(typeof vaultHandle==='undefined'||!vaultHandle||!vaultConnected)return false;
    try{
      var date=_dateStr();
      var dir=vaultHandle;
      dir=await dir.getDirectoryHandle('00-Capture',{create:true});
      var fh=await dir.getFileHandle(date+'.md',{create:true});
      var w=await fh.createWritable();
      await w.write(content);
      await w.close();
      if(typeof spawnBirthParticle==='function')
        spawnBirthParticle('daily','00-Capture/'+date+'.md');
      if(typeof buildGraph==='function')setTimeout(buildGraph,800);
      return true;
    }catch(e){
      console.error('[DAILY] vault write error:',e);
      return false;
    }
  }

  // ── Generate morning briefing via Claude ──────────────────
  async function _generateBriefing(){
    var key=localStorage.getItem('baker_api_key');
    if(!key)return null;
    try{
      // Gather context
      var stData=JSON.parse(localStorage.getItem('baker_strength_v1')||'{}');
      var calData=JSON.parse(localStorage.getItem('baker_cal_v1')||'[]');
      var habData=JSON.parse(localStorage.getItem('baker_habits_v1')||'{}');
      var wxRaw=localStorage.getItem('baker_weather_cache');
      var wx=wxRaw?JSON.parse(wxRaw):null;
      var date=_dateStr();
      var day=_dayName();
      var todayDayIdx=new Date().getDay();
      var splitDay=(stData.split||[]).find(function(s){return s.day===todayDayIdx;});
      var dueToday=calData.filter(function(t){return!t.done&&t.due&&t.due===date;});
      var overdue=calData.filter(function(t){return!t.done&&t.due&&t.due<date;});
      var habLog=((habData.log||{})[date])||{};
      var habDone=(habData.habits||[]).filter(function(h){return habLog[h.id];}).length;
      var habTotal=(habData.habits||[]).length;
      var mem=typeof VAULTSYNC!=='undefined'?VAULTSYNC.getMemoryContext():'';

      var ctx='Date: '+day+', '+date+'\n';
      if(wx)ctx+='Weather: '+Math.round(wx.temp||0)+'°F, '+(wx.desc||'')+'\n';
      ctx+='Workout: '+(splitDay?splitDay.name+' day ('+splitDay.exercises.length+' exercises)':'Rest day')+'\n';
      ctx+='Tasks due today: '+dueToday.length+(overdue.length?' | Overdue: '+overdue.length:'')+'\n';
      if(habTotal)ctx+='Habits: '+habDone+'/'+habTotal+' done today\n';
      if(mem)ctx+='\nUser context:\n'+mem;

      var resp=await fetch('https://api.anthropic.com/v1/messages',{
        method:'POST',
        headers:{'Content-Type':'application/json','x-api-key':key,
          'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},
        body:JSON.stringify({
          model:'claude-sonnet-4-6',
          max_tokens:200,
          messages:[{role:'user',content:
            'You are BAKER, a JARVIS-style AI assistant. Write a sharp, motivating 3-sentence morning briefing for today. '+
            'Reference the specific workout, weather, and tasks. JARVIS tone, address as "sir". No fluff.\n\n'+ctx
          }]
        })
      });
      var d=await resp.json();
      return d.content.map(function(b){return b.text||'';}).join('').trim();
    }catch(e){return null;}
  }

  // ── Main: create/update today's note ─────────────────────
  async function createDailyNote(force){
    var date=_dateStr();

    // Don't spam — only update every 5 minutes unless forced
    if(!force&&_writtenToday&&_today===date&&Date.now()-_lastUpdate<5*60*1000)return;

    _today=date;

    // Generate briefing only once per day
    var briefing=_briefCache;
    if(!briefing||force){
      briefing=await _generateBriefing();
      if(briefing)_briefCache=briefing;
    }

    var content=await _buildNote(briefing);
    var ok=await _writeToVault(content);

    if(ok){
      _writtenToday=true;
      _lastUpdate=Date.now();
      if(typeof setStatus==='function')
        setStatus('Daily note written · '+date);
    }
    return ok;
  }

  // ── Update note without regenerating briefing ─────────────
  async function updateDailyNote(){
    return createDailyNote(false);
  }

  // ── Hook into biometrics save ─────────────────────────────
  function onBiometricsUpdate(){
    if(_writtenToday)setTimeout(updateDailyNote,1500);
  }

  // ── Hook into task completion ─────────────────────────────
  function onTaskUpdate(){
    if(_writtenToday)setTimeout(updateDailyNote,1500);
  }

  // ── Hook into habit completion ────────────────────────────
  function onHabitUpdate(){
    if(_writtenToday)setTimeout(updateDailyNote,1500);
  }

  // ── Init: run on vault connect ────────────────────────────
  function init(){
    // Reset daily state at midnight
    var now=new Date();
    var msUntilMidnight=(new Date(now.getFullYear(),now.getMonth(),now.getDate()+1)-now);
    setTimeout(function(){
      _writtenToday=false;
      _briefCache=null;
      _today=null;
    },msUntilMidnight);
  }

  // ── Voice command ─────────────────────────────────────────
  function handleVoice(cmd){
    var c=cmd.toLowerCase();
    if(/\b(daily|today'?s?)\b.*\b(note|brief|log|summary)\b|\bwrite.*daily\b|\bdaily note\b/.test(c)){
      createDailyNote(true);
      return'Writing your daily note now, sir.';
    }
    if(/\bmorning brief(ing)?\b/.test(c)){
      createDailyNote(true);
      return'Generating your morning briefing, sir.';
    }
    return null;
  }

  return{init,createDailyNote,updateDailyNote,onBiometricsUpdate,onTaskUpdate,onHabitUpdate,handleVoice};
})();
